import {components,categories,defaults} from './components/components.js';
import {createProperties} from './properties.js';
import {visibleCenterPosition} from './placement.js';
import {parseDesignJSON,validateDesignState} from './validation.js';
import {createStore,orderedElements} from './state.js';
import {createJSONEditor} from './json-editor.js';
import {createInlineEditor} from './inline-editor.js';
import {renderCanvas} from './renderer.js';
import {generateHTML,generateCSS,generateDocument} from './exporter.js';
const $=selector=>document.querySelector(selector);
let store,selectedId=null,selectedIds=new Set(),tab='JSON',scale=1,gesture=null,dirty=false,draggedLayer=null,shiftPressed=false,toastTimer;
function notify(message){$('#status').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#status').textContent='',5000);}
const selected=()=>store?.get().elements.find(e=>e.id===selectedId);
function select(id,{additive=false,toggle=false}={}){
  if(!id){selectedIds.clear();selectedId=null;render();return;}
  if(additive){if(toggle&&selectedIds.has(id)){selectedIds.delete(id);if(selectedId===id)selectedId=[...selectedIds].at(-1)??null;}else{selectedIds.add(id);selectedId=id;}}
  else{selectedIds=new Set([id]);selectedId=id;}
  render();
}
function cleanSelection(){if(!store)return;const ids=new Set(store.get().elements.map(e=>e.id));selectedIds=new Set([...selectedIds].filter(id=>ids.has(id)));if(!selectedIds.has(selectedId))selectedId=[...selectedIds].at(-1)??null;}
const jsonEditor=createJSONEditor({editor:$('#json-editor'),apply:$('#apply-json'),reset:$('#reset-json'),message:$('#json-message'),error:$('#json-error'),getState:()=>store.get(),loadState(input,approve){const next=validateDesignState(input);if(!approve())throw new DOMException('取消','AbortError');store.load(next);cleanSelection();notify('JSONを適用しました（Undoできます）');}});
const inlineEditor=createInlineEditor({frame:$('#frame'),getState:()=>store.get(),getScale:()=>scale,commit:(id,text)=>store.update(id,{text}),onChange:()=>{renderSelection();$('#inline-help').hidden=!inlineEditor.isActive();},onError:notify});
const properties=createProperties($('#properties'),{getSelected:selected,update:(id,patch)=>store.update(id,patch),beginChange:()=>store.beginTransaction(),endChange:()=>store.endTransaction()});
function clickPosition(type){return visibleCenterPosition($('#canvas').getBoundingClientRect(),$('#viewport').getBoundingClientRect(),{width:innerWidth,height:innerHeight},store.get().canvas,defaults(type));}
for(const [category,label] of Object.entries(categories)){
  const entries=Object.entries(components).filter(([,c])=>c.category===category);if(!entries.length)continue;
  const section=document.createElement('section');section.className='part-group';section.dataset.category=category;const title=document.createElement('h3');title.textContent=label;section.append(title);const grid=document.createElement('div');grid.className='part-grid';section.append(grid);
  for(const [type,c] of entries){const button=document.createElement('button');button.className='part';button.dataset.type=type;button.draggable=true;button.innerHTML=`<span class="icon" aria-hidden="true">${c.icon}</span>${c.label}`;button.addEventListener('click',()=>{try{select(store.add(type,clickPosition(type)));notify(`${c.label}を追加しました`);}catch(error){notify(error.message);}});button.addEventListener('dragstart',event=>{event.dataTransfer.setData('text/plain',type);event.dataTransfer.effectAllowed='copy';});grid.append(button);}
  $('#parts').append(section);
}
$('#part-total').textContent=Object.keys(components).length;
document.querySelectorAll('.toolbar-menu').forEach(menu=>menu.addEventListener('toggle',()=>{if(menu.open)document.querySelectorAll('.toolbar-menu').forEach(other=>{if(other!==menu)other.open=false;});}));
function fit(){if(!store)return;const viewport=$('#viewport');scale=Math.min((viewport.clientWidth-44)/1440,(viewport.clientHeight-38)/900,1);$('#frame').style.width=`${1440*scale}px`;$('#frame').style.height=`${900*scale}px`;$('#canvas').style.transform=`scale(${scale})`;$('#zoom').textContent=`${Math.round(scale*100)}% · Fit`;renderSelection();inlineEditor.reposition();}
function visualBounds(e){const radians=e.rotation*Math.PI/180,c=Math.abs(Math.cos(radians)),s=Math.abs(Math.sin(radians)),width=e.width*c+e.height*s,height=e.width*s+e.height*c,cx=e.x+e.width/2,cy=e.y+e.height/2;return {left:cx-width/2,right:cx+width/2,top:cy-height/2,bottom:cy+height/2,width,height};}
function groupBounds(items){const boxes=items.map(visualBounds);return {left:Math.min(...boxes.map(b=>b.left)),right:Math.max(...boxes.map(b=>b.right)),top:Math.min(...boxes.map(b=>b.top)),bottom:Math.max(...boxes.map(b=>b.bottom))};}
function renderSelection(){const all=store?.get().elements.filter(e=>selectedIds.has(e.id))??[],box=$('#selection');box.hidden=!all.length||inlineEditor.isActive();if(!all.length)return;const single=all.length===1,e=all[0],bounds=single?{left:e.x,top:e.y,right:e.x+e.width,bottom:e.y+e.height}:groupBounds(all);Object.assign(box.style,{left:`${bounds.left*scale}px`,top:`${bounds.top*scale}px`,width:`${(bounds.right-bounds.left)*scale}px`,height:`${(bounds.bottom-bounds.top)*scale}px`,transform:single?`rotate(${e.rotation}deg)`:'none'});$('#coordinates').textContent=gesture?.mode==='rotate'?`${Math.round(e.rotation)}°`:single?`${e.x}, ${e.y} · ${e.width} × ${e.height}${e.rotation?` · ${e.rotation}°`:''}`:`${all.length} selected`;$('#resize').hidden=!single;$('#rotate').hidden=!single||!['line','arrow'].includes(e.type);}
function renderLayers(state){const layers=$('#layers');layers.replaceChildren();const items=orderedElements(state.elements).reverse();for(const e of items){const item=document.createElement('button');item.className='layer-item';item.draggable=true;item.dataset.layerId=e.id;item.setAttribute('role','option');item.setAttribute('aria-selected',String(selectedIds.has(e.id)));item.innerHTML=`<span>${components[e.type].label}</span><small>${e.id}</small>`;item.addEventListener('click',event=>select(e.id,{additive:event.shiftKey,toggle:event.shiftKey}));item.addEventListener('dragstart',event=>{draggedLayer=e.id;item.classList.add('dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',e.id);});item.addEventListener('dragend',()=>{draggedLayer=null;item.classList.remove('dragging');});item.addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='move';});item.addEventListener('drop',event=>{event.preventDefault();const id=draggedLayer||event.dataTransfer.getData('text/plain'),order=items.map(x=>x.id),from=order.indexOf(id),to=order.indexOf(e.id);if(from<0||to<0||from===to)return;order.splice(from,1);order.splice(to,0,id);store.setLayerOrder(order);select(id);});layers.append(item);}$('#layer-count').textContent=items.length;}
function render(){if(!store)return;cleanSelection();const state=store.get(),e=selected();renderCanvas($('#canvas'),state,selectedIds);renderSelection();renderLayers(state);$('#count').textContent=`${state.elements.length} parts`;$('#selection-count').textContent=`${selectedIds.size} selected`;$('#selected-name').textContent=selectedIds.size>1?`${selectedIds.size}個を選択中`:e?`${components[e.type].label} / ${e.id}`:'パーツを選択してください';$('#properties').hidden=!e||selectedIds.size!==1;$('#empty-selection').hidden=!!e&&selectedIds.size===1;for(const button of document.querySelectorAll('[data-action]'))button.disabled=!selectedIds.size;for(const button of document.querySelectorAll('[data-align]'))button.disabled=selectedIds.size<(button.dataset.align.startsWith('distribute')?3:2);properties.render(selectedIds.size===1?e:null);$('#undo').disabled=!store.canUndo();$('#redo').disabled=!store.canRedo();jsonEditor.sync();$('#json-panel').hidden=tab!=='JSON';$('#code').hidden=tab==='JSON';$('#code').textContent=tab==='CSS'?generateCSS(state):generateHTML(state);$('#code').setAttribute('aria-label',tab);}
function startGesture(event,mode='move'){
  if(event.button!==0)return;inlineEditor.finish();properties.finish();const node=event.target.closest('[data-id]');
  if(mode==='move'){if(!node){select(null);return;}const id=node.dataset.id;if(event.shiftKey){event.preventDefault();select(id,{additive:true,toggle:true});return;}if(!selectedIds.has(id))select(id);}
  const e=selected();if(!e)return;event.preventDefault();const state=store.get(),items=state.elements.filter(x=>selectedIds.has(x.id)),frameRect=$('#frame').getBoundingClientRect(),center={x:frameRect.left+(e.x+e.width/2)*scale,y:frameRect.top+(e.y+e.height/2)*scale};gesture={mode,startX:event.clientX,startY:event.clientY,pointerId:event.pointerId,scale,items,element:e,center,startAngle:Math.atan2(event.clientY-center.y,event.clientX-center.x)*180/Math.PI,started:false};
}
$('#canvas').addEventListener('pointerdown',event=>startGesture(event));$('#resize').addEventListener('pointerdown',event=>startGesture(event,'resize'));$('#rotate').addEventListener('pointerdown',event=>startGesture(event,'rotate'));
$('#canvas').addEventListener('dblclick',event=>{const node=event.target.closest('[data-id]');if(!node||event.shiftKey)return;select(node.dataset.id);inlineEditor.start(node.dataset.id);});
$('#frame').addEventListener('pointermove',event=>{if(!gesture||event.pointerId!==gesture.pointerId)return;const g=gesture,dx=(event.clientX-g.startX)/g.scale,dy=(event.clientY-g.startY)/g.scale;if(!g.started){if(Math.abs(event.clientX-g.startX)<2&&Math.abs(event.clientY-g.startY)<2)return;g.started=true;store.beginTransaction();$('#frame').setPointerCapture(event.pointerId);}if(g.mode==='resize'){store.update(g.element.id,{width:Math.max(1,Math.min(1440-g.element.x,Math.round(g.element.width+dx))),height:Math.max(1,Math.min(900-g.element.y,Math.round(g.element.height+dy)))});return;}if(g.mode==='rotate'){const angle=Math.atan2(event.clientY-g.center.y,event.clientX-g.center.x)*180/Math.PI,raw=g.element.rotation+angle-g.startAngle,rotation=(((event.shiftKey||shiftPressed)?Math.round(raw/15)*15:Math.round(raw))%360+360)%360;store.update(g.element.id,{rotation});return;}const minX=Math.min(...g.items.map(e=>e.x)),maxX=Math.max(...g.items.map(e=>e.x+e.width)),minY=Math.min(...g.items.map(e=>e.y)),maxY=Math.max(...g.items.map(e=>e.y+e.height)),mx=Math.max(-minX,Math.min(1440-maxX,dx)),my=Math.max(-minY,Math.min(900-maxY,dy)),patches=new Map(g.items.map(e=>[e.id,{x:Math.round(e.x+mx),y:Math.round(e.y+my)}]));store.updateMany(patches);});
function endGesture(event){if(!gesture)return;if(gesture.started)store.endTransaction();gesture=null;if($('#frame').hasPointerCapture(event.pointerId))$('#frame').releasePointerCapture(event.pointerId);renderSelection();}
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#frame').addEventListener(name,endGesture);
$('#canvas').addEventListener('dragover',event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';});$('#canvas').addEventListener('drop',event=>{event.preventDefault();const type=event.dataTransfer.getData('text/plain');if(!Object.hasOwn(components,type))return;const rect=$('#canvas').getBoundingClientRect();try{select(store.add(type,{x:Math.round((event.clientX-rect.left)/scale),y:Math.round((event.clientY-rect.top)/scale)}));}catch(error){notify(error.message);}});
function action(name){if(!selectedIds.size)return;properties.finish();const ids=[...selectedIds];if(name==='duplicate'){store.beginTransaction();const copies=ids.map(id=>store.duplicate(id)).filter(Boolean);store.endTransaction();selectedIds=new Set(copies);selectedId=copies.at(-1)??null;render();return;}if(name==='delete'){store.removeMany(ids);select(null);return;}store.beginTransaction();for(const id of ids)store.reorder(id,name);store.endTransaction();render();}
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{try{action(button.dataset.action);}catch(error){notify(error.message);}}));
function align(mode){const state=store.get(),items=state.elements.filter(e=>selectedIds.has(e.id));if(items.length<2)return;const group=groupBounds(items),patches=new Map();if(mode.startsWith('distribute')&&items.length<3)return;if(mode==='distribute-x'){const sorted=[...items].sort((a,b)=>visualBounds(a).left-visualBounds(b).left),sum=sorted.reduce((n,e)=>n+visualBounds(e).width,0),gap=(group.right-group.left-sum)/(sorted.length-1);let cursor=group.left;for(const e of sorted){const b=visualBounds(e);patches.set(e.id,{x:e.x+cursor-b.left});cursor+=b.width+gap;}}else if(mode==='distribute-y'){const sorted=[...items].sort((a,b)=>visualBounds(a).top-visualBounds(b).top),sum=sorted.reduce((n,e)=>n+visualBounds(e).height,0),gap=(group.bottom-group.top-sum)/(sorted.length-1);let cursor=group.top;for(const e of sorted){const b=visualBounds(e);patches.set(e.id,{y:e.y+cursor-b.top});cursor+=b.height+gap;}}else for(const e of items){const b=visualBounds(e),patch={};if(mode==='left')patch.x=e.x+group.left-b.left;if(mode==='center-x')patch.x=e.x+(group.left+group.right-b.left-b.right)/2;if(mode==='right')patch.x=e.x+group.right-b.right;if(mode==='top')patch.y=e.y+group.top-b.top;if(mode==='center-y')patch.y=e.y+(group.top+group.bottom-b.top-b.bottom)/2;if(mode==='bottom')patch.y=e.y+group.bottom-b.bottom;patches.set(e.id,patch);}store.updateMany(patches);notify('選択パーツを整列しました');}
document.querySelectorAll('[data-align]').forEach(button=>button.addEventListener('click',()=>align(button.dataset.align)));
function undo(){properties.finish();inlineEditor.finish();if(store.undo()){cleanSelection();notify('元に戻しました');}}
function redo(){properties.finish();inlineEditor.finish();if(store.redo()){cleanSelection();notify('やり直しました');}}
$('#undo').addEventListener('click',undo);$('#redo').addEventListener('click',redo);
document.addEventListener('keyup',event=>{if(event.key==='Shift')shiftPressed=false;});
document.addEventListener('keydown',event=>{if(event.key==='Shift')shiftPressed=true;const mod=event.metaKey||event.ctrlKey;if(mod&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();return;}if(event.ctrlKey&&event.key.toLowerCase()==='y'){event.preventDefault();redo();return;}if(event.target.closest('input,textarea,select,[contenteditable="true"]')||event.isComposing)return;if(['Delete','Backspace'].includes(event.key)&&selectedIds.size){event.preventDefault();action('delete');}if(event.key==='Escape')select(null);});
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{tab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===button)));render();}));document.querySelector('[role="tablist"]').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(document.activeElement),next=event.key==='Home'?0:event.key==='End'?2:(i+(event.key==='ArrowRight'?1:2))%3;tabs[next].focus();tabs[next].click();});
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('#save').addEventListener('click',()=>{download('design.json',JSON.stringify(store.get(),null,2),'application/json');dirty=false;$('#save-state').textContent='JSON保存済み';notify('design.jsonをダウンロードしました');});$('#export').addEventListener('click',()=>{download('export.html',generateDocument(store.get()),'text/html');notify('単独で表示できるexport.htmlを出力しました');});$('#load').addEventListener('click',()=>$('#file').click());
$('#file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw new Error('JSONファイルは5MB以内にしてください。');const input=validateDesignState(parseDesignJSON(await file.text()));if((dirty||jsonEditor.hasDraft())&&!confirm('未保存の変更またはJSON下書きがあります。JSONを読み込んで置き換えますか？'))return;store.load(input);jsonEditor.discard();select(null);dirty=false;$('#save-state').textContent='JSON読込済み';notify('デザインを復元しました（Undoできます）');}catch(error){notify(`読み込めませんでした: ${error.message}`);}finally{event.target.value='';}});
window.addEventListener('beforeunload',event=>{if(dirty||jsonEditor.hasDraft()||inlineEditor.hasDraft()){event.preventDefault();event.returnValue='';}});
try{const response=await fetch('./samples/following-wind.json');if(!response.ok)throw new Error('サンプル取得に失敗しました');store=createStore(await response.json());store.subscribe(()=>{dirty=true;$('#save-state').textContent='未保存の変更';render();});render();new ResizeObserver(fit).observe($('#viewport'));fit();}catch(error){notify(`起動できませんでした。ページを再読み込みしてください: ${error.message}`);document.querySelectorAll('button').forEach(button=>button.disabled=true);}
