import {components,contentHTML} from './components/components.js';
import {orderedElements} from './state.js';
export const elementStyles=e=>({position:'absolute',left:`${e.x}px`,top:`${e.y}px`,width:`${e.width}px`,height:`${e.height}px`,'font-size':`${e.fontSize}px`,'font-family':e.fontFamily,'font-weight':String(e.fontWeight),'line-height':String(e.lineHeight),'letter-spacing':`${e.letterSpacing}px`,'text-align':e.textAlign,background:e.background,color:e.color,'border-radius':`${e.borderRadius}px`,opacity:String(e.opacity),'z-index':String(e.zIndex),transform:`rotate(${e.rotation}deg)`,'transform-origin':'center center',margin:'0',padding:'0','box-sizing':'border-box','white-space':'pre-wrap','overflow-wrap':'anywhere',overflow:e.type==='arrow'?'visible':'hidden'});
export const borderStyles=e=>({position:'absolute',inset:'0','box-sizing':'border-box','border-color':e.borderColor,'border-width':e.borderWidth+'px','border-style':e.borderStyle,'border-radius':'inherit','pointer-events':'none'});
export const borderHTML=e=>e.borderWidth>0?'<span class="element-border" aria-hidden="true"></span>':'';
const cssRule=(selector,styles)=>selector+' {\n'+Object.entries(styles).map(([k,v])=>'  '+k+': '+v+';').join('\n')+'\n}';
export function generateHTML(state){return `<section class="canvas" aria-label="デザイン">\n${orderedElements(state.elements).map(e=>`  <${components[e.type].tag} class="element ${e.id}">${contentHTML(e)}${borderHTML(e)}</${components[e.type].tag}>`).join('\n')}\n</section>`;}
export function generateCSS(state){return `body { margin: 0; }\n.canvas {\n  position: relative;\n  isolation: isolate;\n  overflow: hidden;\n  width: ${state.canvas.width}px;\n  height: ${state.canvas.height}px;\n  background: ${state.canvas.background};\n  font-family: Arial, "Noto Sans", sans-serif;\n}\n\n${orderedElements(state.elements).map(e=>cssRule('.'+e.id,elementStyles(e))+(e.borderWidth>0?'\n'+cssRule('.'+e.id+' > .element-border',borderStyles(e)):'' )).join('\n\n')}`;}
export const generateDocument=state=>`<!doctype html>\n<html lang="ja">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>Following Wind — Design</title>\n<style>\n${generateCSS(state)}\n</style>\n</head>\n<body>\n${generateHTML(state)}\n</body>\n</html>\n`;
