import {createCropper} from './cropper.js';
import {copyCanvasImage,copyText,downloadCanvasPng} from './export.js';
import {imageFileFromTransfer,loadImageFile} from './image-loader.js';
import {PALETTE_MODES} from './palettes.js';
import {countColors,processImage} from './pixelizer.js';
import {decodeCompact,encodeCompact,generateCompactCode,rgbaMatchPercent} from './sprite-codec.js';
const $=selector=>document.querySelector(selector),state={image:null,size:256,mode:'adaptive32',pixelData:null,renderTimer:null};
const outputCanvas=$('#pixel-canvas'),outputContext=outputCanvas.getContext('2d'),cropper=createCropper($('#crop-canvas'),scheduleRender);let toastTimer;
function notify(message,error=false){$('#toast').textContent=message;$('#toast').classList.toggle('error',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',4200);}
function scheduleRender(){clearTimeout(state.renderTimer);state.renderTimer=setTimeout(renderPixelized,70);}
function renderPixelized(){
  if(!state.image)return;state.pixelData=processImage({image:state.image,crop:cropper.getCrop(),size:state.size,mode:state.mode});outputCanvas.width=state.pixelData.width;outputCanvas.height=state.pixelData.height;outputContext.imageSmoothingEnabled=false;outputContext.putImageData(new ImageData(state.pixelData.rgba,state.pixelData.width,state.pixelData.height),0,0);
  const compact=encodeCompact(state.pixelData),match=rgbaMatchPercent(state.pixelData.rgba,decodeCompact(compact));$('#result-size').textContent=`${state.size} × ${state.size}`;$('#result-palette').textContent=PALETTE_MODES[state.mode].label;$('#result-colors').textContent=countColors(state.pixelData.rgba);$('#code-match').textContent=`CODE MATCH ${match}%`;$('#code-match').classList.toggle('bad',match!==100);$('#result-panel').hidden=false;
}
async function useFile(file){try{state.image=await loadImageFile(file);cropper.setImage(state.image);$('#source-meta').textContent=`${state.image.naturalWidth} × ${state.image.naturalHeight} · ${file.type.replace('image/','').toUpperCase()}`;$('#drop-zone').classList.add('loaded');$('#drop-title').textContent='画像を入れ替える';renderPixelized();notify('画像を読み込みました。Crop枠をドラッグして位置を調整できます。');}catch(error){notify(error.message,true);}}
$('#file-input').addEventListener('change',event=>{if(event.target.files[0])useFile(event.target.files[0]);event.target.value='';});$('#drop-zone').addEventListener('click',event=>{if(!event.target.closest('button'))$('#file-input').click();});$('#choose-file').addEventListener('click',event=>{event.stopPropagation();$('#file-input').click();});$('#paste-button').addEventListener('click',event=>{event.stopPropagation();notify('このページ上で Ctrl / ⌘ + V を押してください。');});
$('#drop-zone').addEventListener('dragover',event=>{event.preventDefault();$('#drop-zone').classList.add('dragover');});$('#drop-zone').addEventListener('dragleave',()=>$('#drop-zone').classList.remove('dragover'));$('#drop-zone').addEventListener('drop',event=>{event.preventDefault();$('#drop-zone').classList.remove('dragover');const file=imageFileFromTransfer(event.dataTransfer);if(file)useFile(file);else notify('PNG / JPEG / WebP画像をドロップしてください。',true);});window.addEventListener('paste',event=>{if(event.target.closest('input,textarea'))return;const file=imageFileFromTransfer(event.clipboardData);if(file){event.preventDefault();useFile(file);}});
document.querySelectorAll('[data-size]').forEach(button=>button.addEventListener('click',()=>{state.size=Number(button.dataset.size);document.querySelectorAll('[data-size]').forEach(item=>item.classList.toggle('active',item===button));scheduleRender();}));document.querySelectorAll('[data-palette]').forEach(button=>button.addEventListener('click',()=>{state.mode=button.dataset.palette;document.querySelectorAll('[data-palette]').forEach(item=>item.classList.toggle('active',item===button));scheduleRender();}));
$('#zoom').addEventListener('input',event=>{cropper.setZoom(event.target.value);$('#zoom-value').textContent=`${Number(event.target.value).toFixed(1)}×`;});$('#center-crop').addEventListener('click',()=>cropper.center());$('#reset-crop').addEventListener('click',()=>{$('#zoom').value=1;$('#zoom-value').textContent='1.0×';cropper.reset();});
$('#copy-image').addEventListener('click',async()=>{if(!state.pixelData)return;try{await copyCanvasImage(outputCanvas);notify('PNG画像をコピーしました。Asepriteで貼り付けできます。');}catch(error){notify(error.message,true);}});$('#download-png').addEventListener('click',async()=>{if(!state.pixelData)return;try{const colors=state.mode==='adaptive32'?'32colors':state.mode==='adaptive16'?'16colors':'pyxel16';await downloadCanvasPng(outputCanvas,`pixelized-${state.size}-${colors}.png`);notify(`${state.size}×${state.size} PNGを保存しました。`);}catch(error){notify(error.message,true);}});$('#copy-code').addEventListener('click',async()=>{if(!state.pixelData)return;try{await copyText(generateCompactCode(state.pixelData,$('#sprite-name').value));notify('Canvas JavaScriptコードをコピーしました。');}catch(error){notify(error.message,true);}});
window.pixelizerQA={state,cropper,renderPixelized,encodeCompact,decodeCompact};
