const PALETTE_TOKENS='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
export function jsVariableName(name){let value=String(name||'PIXEL_ART').trim().toUpperCase().replace(/[^A-Z0-9_$]+/g,'_').replace(/^_+|_+$/g,'');if(!value)value='PIXEL_ART';if(/^[0-9]/.test(value))value=`PIXEL_ART_${value}`;return value;}
export function encodeCompact({width,height,rgba}){
  if(rgba.length!==width*height*4)throw new Error('RGBAデータと画像サイズが一致しません。');const palette={'.':null},tokenByColor=new Map(),rows=[];
  for(let y=0;y<height;y++){let row='';for(let x=0;x<width;x++){const index=(y*width+x)*4,a=rgba[index+3];if(a===0){row+='.';continue;}const color=[rgba[index],rgba[index+1],rgba[index+2],a],key=color.join(',');let token=tokenByColor.get(key);if(!token){if(tokenByColor.size>=PALETTE_TOKENS.length)throw new Error('Compact形式の上限色数を超えています。');token=PALETTE_TOKENS[tokenByColor.size];tokenByColor.set(key,token);palette[token]=color;}row+=token;}rows.push(row);}return {width,height,palette,rows};
}
export function decodeCompact(sprite){const rgba=new Uint8ClampedArray(sprite.width*sprite.height*4);if(sprite.rows.length!==sprite.height)throw new Error('Rowsの行数が不正です。');for(let y=0;y<sprite.height;y++){const row=sprite.rows[y];if(row.length!==sprite.width)throw new Error('Rowsの幅が不正です。');for(let x=0;x<sprite.width;x++){const color=sprite.palette[row[x]];if(color)rgba.set(color,(y*sprite.width+x)*4);}}return rgba;}
export function rgbaMatchPercent(a,b){if(a.length!==b.length)return 0;let matching=0;for(let i=0;i<a.length;i++)if(a[i]===b[i])matching++;return Math.round(matching/a.length*10000)/100;}
function spriteLiteral(sprite){const palette=Object.entries(sprite.palette).map(([token,color])=>`    ${JSON.stringify(token)}: ${color?`[${color.join(', ')}]`:'null'}`).join(',\n');const rows=sprite.rows.map(row=>`    ${JSON.stringify(row)}`).join(',\n');return `{\n  width: ${sprite.width},\n  height: ${sprite.height},\n  palette: {\n${palette}\n  },\n  rows: [\n${rows}\n  ]\n}`;}
export function generateCompactCode(pixelData,requestedName='PIXEL_ART'){
  const name=jsVariableName(requestedName),sprite=encodeCompact(pixelData);
  return `const ${name} = ${spriteLiteral(sprite)};\n\nfunction drawPixelSprite(ctx, sprite, x, y, scale = 1) {\n  for (let py = 0; py < sprite.height; py++) {\n    const row = sprite.rows[py];\n    for (let px = 0; px < sprite.width; px++) {\n      const color = sprite.palette[row[px]];\n      if (!color) continue;\n      const [r, g, b, a] = color;\n      ctx.fillStyle = 'rgba(' + r + ', ' + g + ', ' + b + ', ' + (a / 255) + ')';\n      ctx.fillRect(x + px * scale, y + py * scale, scale, scale);\n    }\n  }\n}\n\n// 128 / 256pxの静止画は一度だけCanvasへ描き、ゲーム中はdrawImageします。\nfunction buildPixelSpriteCanvas(sprite) {\n  const canvas = document.createElement('canvas');\n  canvas.width = sprite.width;\n  canvas.height = sprite.height;\n  const cacheContext = canvas.getContext('2d');\n  drawPixelSprite(cacheContext, sprite, 0, 0, 1);\n  return canvas;\n}\n\nconst ${name}_CANVAS = buildPixelSpriteCanvas(${name});\n\n// game loop example\nctx.imageSmoothingEnabled = false;\nctx.drawImage(${name}_CANVAS, 0, 0);`;
}
